//GET
const GET_BITCOIN_DATA = "GET_BITCOIN_DATA";
const GET_BITCOIN_DATA_SUCCESS = "GET_BITCOIN_DATA_SUCCESS";
const GET_BITCOIN_DATA_FAILURE = "GET_BITCOIN_DATA_FAILURE";

//ADD
const ADD_BITCOIN_DATA = "ADD_BITCOIN_DATA";
const ADD_BITCOIN_DATA_SUCCESS = "ADD_BITCOIN_DATA_SUCCESS";
const ADD_BITCOIN_DATA_FAILURE = "ADD_BITCOIN_DATA_FAILURE";

//UPDATE
const UPDATE_BITCOIN_DATA = "UPDATE_BITCOIN_DATA";
const UPDATE_BITCOIN_DATA_SUCCESS = "UPDATE_BITCOIN_DATA_SUCCESS";
const UPDATE_BITCOIN_DATA_FAILURE = "UPDATE_BITCOIN_DATA_FAILURE";

//DELETE
const REMOVE_BITCOIN_DATA = "REMOVE_BITCOIN_DATA";
const REMOVE_BITCOIN_DATA_SUCCESS = "REMOVE_BITCOIN_DATA_SUCCESS";
const REMOVE_BITCOIN_DATA_FAILURE = "REMOVE_BITCOIN_DATA_FAILURE";


export {
    GET_BITCOIN_DATA,
    GET_BITCOIN_DATA_SUCCESS,
    GET_BITCOIN_DATA_FAILURE
}